### ISSUE TITLE
Farmer cannot click reload under the following circumstances

### ISSUE THREAD

**Issue by fwaierr** [farshadz1997/Microsoft-Rewards-bot#183] opened 2023-03-23 13:30 UTC
When encountering an http504 error, it can be resolved by clicking reload, but the farmbot does not seem to click, resulting in an endless loop under the page (starting from scratch, repeatedly encountering http504 errors)

**Comment by farshadz1997** [comment] 2023-03-23 15:03
This error comes from MS, wait for them to fix it, I cannot implement this for all over the bot.

**Comment by Giovix92** [comment] 2023-03-23 17:49
> This error comes from MS, wait for them to fix it, I cannot implement this for all over the bot.

Could be useful a reload when the webdriver detects the 501/504 error, instead of relaunching the whole browser.

**Comment by Prabh-Saini** [comment] 2023-03-26 10:03
@Giovix92 the issue is that its a lot of work for a minor issue that is simply resolved and the only penalty is less than a minute of the bot's time. sure in an ideal world it would be very nice to detect for all status codes except for 200 and from there reload or determine the best solution from thereafter.

**Comment by Prabh-Saini** [comment] 2023-04-06 02:30
@farshadz1997 can we close this as unplanned?

**Closed** 2023-04-06 09:24 UTC
