### ISSUE TITLE
Update.py issues

### ISSUE THREAD

**Issue by tommaso-ascani** [farshadz1997/Microsoft-Rewards-bot#209] opened 2023-04-03 22:21 UTC
When i exec py update.py --update, it downloads the files even if my version is the latest (ms_rewards_farmer.py returns i'm up to date), and 'git diff' returns me this warnings:
```
warning: in the working copy of 'README.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'ms_rewards_farmer.py', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'requirements.txt', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'searchwords.txt', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'setup.md', LF will be replaced by CRLF the next time Git touches it
```
It seems the downloaded files has different /r and /n characters from the files cloned or pulled by git

**Comment by farshadz1997** [comment] 2023-04-03 22:40
@Prabh-Saini could you please check updater?

**Comment by Prabh-Saini** [comment] 2023-04-03 23:26
> When i exec py update.py --update, it downloads the files even if my version is the latest (ms_rewards_farmer.py returns i'm up to date), and 'git diff' returns me this warnings:
> 
> ```
> warning: in the working copy of 'README.md', LF will be replaced by CRLF the next time Git touches it
> warning: in the working copy of 'ms_rewards_farmer.py', LF will be replaced by CRLF the next time Git touches it
> warning: in the working copy of 'requirements.txt', LF will be replaced by CRLF the next time Git touches it
> warning: in the working copy of 'searchwords.txt', LF will be replaced by CRLF the next time Git touches it
> warning: in the working copy of 'setup.md', LF will be replaced by CRLF the next time Git touches it
> ```
> 
> It seems the downloaded files has different /r and /n characters from the files cloned or pulled by git

From my research it looks like it's caused by new lines (as you suggested), only for people with Git. I don't have Git so I'm not really one that could help, but it doesn't look very important so you can probably just ignore it.

**Comment by Giovix92** [comment] 2023-04-04 09:39
You could fix it by running `git config core.autocrlf false` inside your current repo.
It basically disables the warning by NOT converting LF-styled files to CRLF.

@Prabh-Saini I guess you could add this by just running an os.system() before pulling the repository, or add a new .gitattributes with these lines:
```
[core]
	autocrlf = false
```

**Comment by Prabh-Saini** [comment] 2023-04-04 09:47
well i don't want to run this and change somebody elses global git settings, so theres no real fix and it is what it is. i think it is best to simply close this issue @farshadz1997

**Closed** 2023-04-04 09:49 UTC

**Comment by Giovix92** [comment] 2023-04-04 09:59
> well i don't want to run this and change somebody elses global git settings, so theres no real fix and it is what it is. i think it is best to simply close this issue @farshadz1997

it'd be global if you'd add the `--global` to the command. As you wish tho.
